---
version: 1.0.105
slug: dynu_updater
name: Dynu Domain Update Tool
description: Update dynamic DNS and generate certificates for a domain registerd with dynu.com
url: https://github.com/TheUkShadow/HA-Addons/tree/main/dynu-updater
hassio_api: true
hassio_role: manager
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
boot: auto
init: false
map:
  - ssl:rw
  - share
options:
  dns.update_ip: true
  cert.update_cert: true
  cert.keyfile: privkey.pem
  cert.certfile: fullchain.pem
  mqtt.mqtt_key: privkey.pem
  mqtt.mqtt_cert: fullchain.pem
  cert.update_cert_days: 5
schema:
  dynu_hostname: str
  dynu_api_key: password
  dns:
    update_ip: bool
    dynu_update_password: password
    ip_domains:
      - str
  cert:
    update_cert: bool
    email: email
    update_cert_days: int(1,30)
    domains:
      - str 
    keyfile: str
    certfile: str
    restart_addons:
      - str?
    force_renew: bool?
    dry_run: bool?
  mqtt:
    mqtt_enabled: bool?
    mqtt_host: str?
    mqtt_port: int?
    mqtt_user: str?
    mqtt_password: password?
    mqtt_tls: bool?
    mqtt_key: str?
    mqtt_cert: str?
  verbose: bool?

startup: services