---
version: 1.0.6
slug: dynu_updater
name: Dynu Domain Update Tool
description: Update dynamic DNS and generate certificates for a domain registerd with dynu.com
url: https://github.com/TheUkShadow/HA-Addons/tree/main/dynu-updater
hassio_api: true
hassio_role: manager
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
boot: auto
init: false
map:
  - ssl:rw
  - share
options:
  dns:
    update_ip: true
  cert:
    update_cert: true
    keyfile: privkey.pem
    certfile: fullchain.pem
    update_cert_days: 5
    force_renew: false
    dry_run: false
  mqtt:
    enabled: false
    core: true
    host: core-mosquitto
    port: 1883
    tls: false
    server_cert: true
  verbose: false
schema:
  dynu_hostname: str
  dynu_api_key: password
  dns:
    update_ip: bool
    dynu_update_password: password?
    domains:
      - str?
  cert:
    update_cert: bool
    email: email?
    update_cert_days: int(1,30)
    domains:
      - str?
    keyfile: str?
    certfile: str?
    force_renew: bool
    dry_run: bool
  mqtt:
    enabled: bool
    core: bool
    host: str?
    port: int?
    user: str?
    password: password?
    tls: bool
    server_cert: bool
    keyfile: str?
    certfile: str?
    cafile: str?
  verbose: bool

startup: services