---
version: 1.0.74
slug: dynu_updater
name: Dynu Domain Update Tool
description: Update dynamic DNS and generate certificates for a domain registerd with dynu.com
url: https://github.com/TheUkShadow/HA-Addons/tree/main/dynu-updater
hassio_api: true
hassio_role: manager
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
boot: auto
init: false
map:
  - ssl:rw
  - share
options:
  update_ip: true
  update_cert: true
  keyfile: privkey.pem
  certfile: fullchain.pem
  update_cert_days: 5
schema:
  dynu_hostname: str
  dynu_update_password: password
  dynu_api_key: password
  email: email
  update_ip: bool
  ip_domains:
    - str
  update_cert: bool
  update_cert_days: int(1,30)
  domains:
    - str 
  keyfile: str
  certfile: str
  restart_addons:
    - str?
  mqtt: bool?
  mqtt_host: str?
  mqtt_port: int?
  mqtt_user: str?
  mqtt_password: password?
  verbose: bool?
  force_renew: bool?
  dry_run: bool?

startup: services