#!/usr/bin/with-contenv bash
# shellcheck shell=bash

USE_MQTT=$(bashio::config 'mqtt' 'false')
# Publish offline availability
if [[ "$USE_MQTT" == "true" ]]; then
	bashio::log.info "Dynu Updater Closing - Sending offline signal to MQTT"
	mosquitto_pub \
		-h "$MQTT_HOST" \
		-u "$MQTT_USER" \
		-P "$MQTT_PASSWORD" \
		-t "dynu_updater/availability" \
		-m "offline" \
		-r
fi